env:
  browser: true
  es6: true
  node: true
  jest: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - jest
rules:
  indent: ['off']
  semi: ['error', 'never']
  quotes: ['error', 'single']
  no-underscore-dangle: ['off']
  space-before-function-paren: ['off']
